BeginnerClearing_MapScripts::
	.byte 0


# 5 "data/maps/BeginnerClearing/scripts.pory"
BeginnerClearing_ExclamationMark:
# 6 "data/maps/BeginnerClearing/scripts.pory"
	emote_exclamation_mark
	step_end

# 9 "data/maps/BeginnerClearing/scripts.pory"
BeginnerClearing_QuestionMark:
# 10 "data/maps/BeginnerClearing/scripts.pory"
	emote_question_mark
	step_end

# 13 "data/maps/BeginnerClearing/scripts.pory"
BeginnerClearing_WalkUpToJirachiFromA:
# 14 "data/maps/BeginnerClearing/scripts.pory"
	walk_fast_right
# 14 "data/maps/BeginnerClearing/scripts.pory"
	walk_fast_right
# 14 "data/maps/BeginnerClearing/scripts.pory"
	walk_fast_right
# 14 "data/maps/BeginnerClearing/scripts.pory"
	walk_fast_right
# 14 "data/maps/BeginnerClearing/scripts.pory"
	walk_fast_right
# 15 "data/maps/BeginnerClearing/scripts.pory"
	walk_fast_up
# 15 "data/maps/BeginnerClearing/scripts.pory"
	walk_fast_up
# 16 "data/maps/BeginnerClearing/scripts.pory"
	face_right
	step_end

# 19 "data/maps/BeginnerClearing/scripts.pory"
BeginnerClearing_WalkUpToJirachiFromB:
# 20 "data/maps/BeginnerClearing/scripts.pory"
	walk_fast_right
# 20 "data/maps/BeginnerClearing/scripts.pory"
	walk_fast_right
# 20 "data/maps/BeginnerClearing/scripts.pory"
	walk_fast_right
# 20 "data/maps/BeginnerClearing/scripts.pory"
	walk_fast_right
# 20 "data/maps/BeginnerClearing/scripts.pory"
	walk_fast_right
# 21 "data/maps/BeginnerClearing/scripts.pory"
	walk_fast_up
# 21 "data/maps/BeginnerClearing/scripts.pory"
	walk_fast_up
# 21 "data/maps/BeginnerClearing/scripts.pory"
	walk_fast_up
# 22 "data/maps/BeginnerClearing/scripts.pory"
	face_right
	step_end

# 25 "data/maps/BeginnerClearing/scripts.pory"
BeginnerClearing_MyraRunsInA:
# 26 "data/maps/BeginnerClearing/scripts.pory"
	walk_fast_right
# 26 "data/maps/BeginnerClearing/scripts.pory"
	walk_fast_right
# 26 "data/maps/BeginnerClearing/scripts.pory"
	walk_fast_right
	step_end

# 29 "data/maps/BeginnerClearing/scripts.pory"
BeginnerClearing_MyraRunsInB:
# 30 "data/maps/BeginnerClearing/scripts.pory"
	walk_fast_right
# 30 "data/maps/BeginnerClearing/scripts.pory"
	walk_fast_right
# 30 "data/maps/BeginnerClearing/scripts.pory"
	walk_fast_right
# 30 "data/maps/BeginnerClearing/scripts.pory"
	walk_fast_right
# 30 "data/maps/BeginnerClearing/scripts.pory"
	walk_fast_right
# 30 "data/maps/BeginnerClearing/scripts.pory"
	walk_fast_right
# 31 "data/maps/BeginnerClearing/scripts.pory"
	walk_fast_up
	step_end

# 34 "data/maps/BeginnerClearing/scripts.pory"
BeginnerClearing_GruntAWalksIn:
# 35 "data/maps/BeginnerClearing/scripts.pory"
	walk_fast_right
# 35 "data/maps/BeginnerClearing/scripts.pory"
	walk_fast_right
# 35 "data/maps/BeginnerClearing/scripts.pory"
	walk_fast_right
# 35 "data/maps/BeginnerClearing/scripts.pory"
	walk_fast_right
	step_end

# 38 "data/maps/BeginnerClearing/scripts.pory"
BeginnerClearing_GruntBWalksIn:
# 39 "data/maps/BeginnerClearing/scripts.pory"
	walk_fast_right
# 39 "data/maps/BeginnerClearing/scripts.pory"
	walk_fast_right
# 39 "data/maps/BeginnerClearing/scripts.pory"
	walk_fast_right
# 39 "data/maps/BeginnerClearing/scripts.pory"
	walk_fast_right
# 39 "data/maps/BeginnerClearing/scripts.pory"
	walk_fast_right
	step_end

# 42 "data/maps/BeginnerClearing/scripts.pory"
BeginnerClearing_PlayerRunsInFrontOfGrunts:
# 43 "data/maps/BeginnerClearing/scripts.pory"
	walk_fast_down
# 43 "data/maps/BeginnerClearing/scripts.pory"
	walk_fast_down
# 44 "data/maps/BeginnerClearing/scripts.pory"
	walk_fast_left
# 45 "data/maps/BeginnerClearing/scripts.pory"
	face_left
	step_end

# 48 "data/maps/BeginnerClearing/scripts.pory"
BeginnerClearing_ProfMyraWalksToPlayer:
# 49 "data/maps/BeginnerClearing/scripts.pory"
	walk_down
# 49 "data/maps/BeginnerClearing/scripts.pory"
	walk_down
# 50 "data/maps/BeginnerClearing/scripts.pory"
	walk_left
# 50 "data/maps/BeginnerClearing/scripts.pory"
	walk_left
	step_end

# 53 "data/maps/BeginnerClearing/scripts.pory"
BeginnerClearing_GruntARunsToPlayer:
# 54 "data/maps/BeginnerClearing/scripts.pory"
	walk_fast_right
# 54 "data/maps/BeginnerClearing/scripts.pory"
	walk_fast_right
# 54 "data/maps/BeginnerClearing/scripts.pory"
	walk_fast_right
# 54 "data/maps/BeginnerClearing/scripts.pory"
	walk_fast_right
	step_end

# 57 "data/maps/BeginnerClearing/scripts.pory"
BeginnerClearing_GruntBRunsToProfMyra:
# 58 "data/maps/BeginnerClearing/scripts.pory"
	walk_fast_right
# 58 "data/maps/BeginnerClearing/scripts.pory"
	walk_fast_right
# 58 "data/maps/BeginnerClearing/scripts.pory"
	walk_fast_right
	step_end

# 61 "data/maps/BeginnerClearing/scripts.pory"
BeginnerClearing_WalkToGruntA_LeftSideOfBag:
# 62 "data/maps/BeginnerClearing/scripts.pory"
	walk_fast_down
# 63 "data/maps/BeginnerClearing/scripts.pory"
	walk_fast_left
	step_end

# 66 "data/maps/BeginnerClearing/scripts.pory"
BeginnerClearing_WalkToGruntA_TopSideOfBag:
# 67 "data/maps/BeginnerClearing/scripts.pory"
	walk_fast_right
# 68 "data/maps/BeginnerClearing/scripts.pory"
	walk_fast_down
# 68 "data/maps/BeginnerClearing/scripts.pory"
	walk_fast_down
# 69 "data/maps/BeginnerClearing/scripts.pory"
	walk_fast_left
# 69 "data/maps/BeginnerClearing/scripts.pory"
	walk_fast_left
# 69 "data/maps/BeginnerClearing/scripts.pory"
	walk_fast_left
	step_end

# 72 "data/maps/BeginnerClearing/scripts.pory"
BeginnerClearing_WalkToGruntA_RightSideOfBag:
# 73 "data/maps/BeginnerClearing/scripts.pory"
	walk_fast_down
# 74 "data/maps/BeginnerClearing/scripts.pory"
	walk_fast_left
# 74 "data/maps/BeginnerClearing/scripts.pory"
	walk_fast_left
# 74 "data/maps/BeginnerClearing/scripts.pory"
	walk_fast_left
	step_end

# 77 "data/maps/BeginnerClearing/scripts.pory"
BeginnerClearing_WalkToGruntA_BottomSideOfBag:
# 78 "data/maps/BeginnerClearing/scripts.pory"
	walk_fast_left
# 78 "data/maps/BeginnerClearing/scripts.pory"
	walk_fast_left
	step_end

# 81 "data/maps/BeginnerClearing/scripts.pory"
BeginnerClearing_PlayerWalksIn_LookForJirachiFromA:
# 82 "data/maps/BeginnerClearing/scripts.pory"
	delay_16
# 83 "data/maps/BeginnerClearing/scripts.pory"
	walk_right
# 83 "data/maps/BeginnerClearing/scripts.pory"
	walk_right
# 83 "data/maps/BeginnerClearing/scripts.pory"
	walk_right
# 83 "data/maps/BeginnerClearing/scripts.pory"
	walk_right
# 83 "data/maps/BeginnerClearing/scripts.pory"
	walk_right
# 83 "data/maps/BeginnerClearing/scripts.pory"
	walk_right
# 83 "data/maps/BeginnerClearing/scripts.pory"
	walk_right
# 84 "data/maps/BeginnerClearing/scripts.pory"
	walk_up
# 85 "data/maps/BeginnerClearing/scripts.pory"
	delay_16
# 86 "data/maps/BeginnerClearing/scripts.pory"
	delay_16
# 87 "data/maps/BeginnerClearing/scripts.pory"
	face_left
# 88 "data/maps/BeginnerClearing/scripts.pory"
	delay_16
# 89 "data/maps/BeginnerClearing/scripts.pory"
	delay_16
# 90 "data/maps/BeginnerClearing/scripts.pory"
	delay_16
# 91 "data/maps/BeginnerClearing/scripts.pory"
	face_right
# 92 "data/maps/BeginnerClearing/scripts.pory"
	delay_16
# 93 "data/maps/BeginnerClearing/scripts.pory"
	delay_16
# 94 "data/maps/BeginnerClearing/scripts.pory"
	delay_16
# 95 "data/maps/BeginnerClearing/scripts.pory"
	face_up
	step_end

# 98 "data/maps/BeginnerClearing/scripts.pory"
BeginnerClearing_PlayerWalksIn_LookForJirachiFromB:
# 99 "data/maps/BeginnerClearing/scripts.pory"
	delay_16
# 100 "data/maps/BeginnerClearing/scripts.pory"
	walk_right
# 100 "data/maps/BeginnerClearing/scripts.pory"
	walk_right
# 100 "data/maps/BeginnerClearing/scripts.pory"
	walk_right
# 100 "data/maps/BeginnerClearing/scripts.pory"
	walk_right
# 100 "data/maps/BeginnerClearing/scripts.pory"
	walk_right
# 100 "data/maps/BeginnerClearing/scripts.pory"
	walk_right
# 100 "data/maps/BeginnerClearing/scripts.pory"
	walk_right
# 101 "data/maps/BeginnerClearing/scripts.pory"
	walk_up
# 101 "data/maps/BeginnerClearing/scripts.pory"
	walk_up
# 102 "data/maps/BeginnerClearing/scripts.pory"
	delay_16
# 103 "data/maps/BeginnerClearing/scripts.pory"
	delay_16
# 104 "data/maps/BeginnerClearing/scripts.pory"
	face_left
# 105 "data/maps/BeginnerClearing/scripts.pory"
	delay_16
# 106 "data/maps/BeginnerClearing/scripts.pory"
	delay_16
# 107 "data/maps/BeginnerClearing/scripts.pory"
	delay_16
# 108 "data/maps/BeginnerClearing/scripts.pory"
	face_right
# 109 "data/maps/BeginnerClearing/scripts.pory"
	delay_16
# 110 "data/maps/BeginnerClearing/scripts.pory"
	delay_16
# 111 "data/maps/BeginnerClearing/scripts.pory"
	delay_16
# 112 "data/maps/BeginnerClearing/scripts.pory"
	face_up
	step_end

BeginnerClearing_EventScript_WalkFromA::
# 132 "data/maps/BeginnerClearing/scripts.pory"
	lockall
# 133 "data/maps/BeginnerClearing/scripts.pory"
	goto_if_unset FLAG_CAN_LEAVE_BEGINNER_CLEARING, BeginnerClearing_EventScript_WalkFromA_2
BeginnerClearing_EventScript_WalkFromA_1:
# 144 "data/maps/BeginnerClearing/scripts.pory"
	releaseall
	return

BeginnerClearing_EventScript_WalkFromA_2:
# 134 "data/maps/BeginnerClearing/scripts.pory"
	playmoncry SPECIES_JIRACHI, CRY_MODE_FAINT
# 135 "data/maps/BeginnerClearing/scripts.pory"
	waitmoncry
# 136 "data/maps/BeginnerClearing/scripts.pory"
	applymovement LOCALID_PLAYER, BeginnerClearing_ExclamationMark
# 137 "data/maps/BeginnerClearing/scripts.pory"
	playse SE_PIN
# 138 "data/maps/BeginnerClearing/scripts.pory"
	waitmovement 0
# 139 "data/maps/BeginnerClearing/scripts.pory"
	delay 50
# 140 "data/maps/BeginnerClearing/scripts.pory"
	applymovement LOCALID_PLAYER, BeginnerClearing_WalkUpToJirachiFromA
# 141 "data/maps/BeginnerClearing/scripts.pory"
	waitmovement 0
# 142 "data/maps/BeginnerClearing/scripts.pory"
	call BeginnerClearing_EventScript_JirachiIntro
	goto BeginnerClearing_EventScript_WalkFromA_1


BeginnerClearing_EventScript_WalkFromB::
# 148 "data/maps/BeginnerClearing/scripts.pory"
	lockall
# 149 "data/maps/BeginnerClearing/scripts.pory"
	goto_if_unset FLAG_CAN_LEAVE_BEGINNER_CLEARING, BeginnerClearing_EventScript_WalkFromB_2
BeginnerClearing_EventScript_WalkFromB_1:
# 160 "data/maps/BeginnerClearing/scripts.pory"
	releaseall
	return

BeginnerClearing_EventScript_WalkFromB_2:
# 150 "data/maps/BeginnerClearing/scripts.pory"
	playmoncry SPECIES_JIRACHI, CRY_MODE_FAINT
# 151 "data/maps/BeginnerClearing/scripts.pory"
	waitmoncry
# 152 "data/maps/BeginnerClearing/scripts.pory"
	applymovement LOCALID_PLAYER, BeginnerClearing_ExclamationMark
# 153 "data/maps/BeginnerClearing/scripts.pory"
	playse SE_PIN
# 154 "data/maps/BeginnerClearing/scripts.pory"
	waitmovement 0
# 155 "data/maps/BeginnerClearing/scripts.pory"
	delay 50
# 156 "data/maps/BeginnerClearing/scripts.pory"
	applymovement LOCALID_PLAYER, BeginnerClearing_WalkUpToJirachiFromB
# 157 "data/maps/BeginnerClearing/scripts.pory"
	waitmovement 0
# 158 "data/maps/BeginnerClearing/scripts.pory"
	call BeginnerClearing_EventScript_JirachiIntro
	goto BeginnerClearing_EventScript_WalkFromB_1


BeginnerClearing_EventScript_ProfMyra::
# 164 "data/maps/BeginnerClearing/scripts.pory"
	speakername ProfMyraName
# 165 "data/maps/BeginnerClearing/scripts.pory"
	msgbox BeginnerClearing_EventScript_ProfMyra_Text_0, MSGBOX_NPC
	return


BeginnerClearing_EventScript_GruntA::
# 170 "data/maps/BeginnerClearing/scripts.pory"
	speakername GruntAName
# 171 "data/maps/BeginnerClearing/scripts.pory"
	msgbox BeginnerClearing_EventScript_GruntA_Text_0, MSGBOX_NPC
	return


BeginnerClearing_EventScript_GruntB::
# 175 "data/maps/BeginnerClearing/scripts.pory"
	speakername GruntBName
# 176 "data/maps/BeginnerClearing/scripts.pory"
	msgbox BeginnerClearing_EventScript_GruntB_Text_0, MSGBOX_NPC
	return


BeginnerClearing_EventScript_JirachiNPC::
# 180 "data/maps/BeginnerClearing/scripts.pory"
	playmoncry SPECIES_JIRACHI, CRY_MODE_FAINT
# 181 "data/maps/BeginnerClearing/scripts.pory"
	waitmoncry
	return


BeginnerClearing_EventScript_JirachiIntro::
# 185 "data/maps/BeginnerClearing/scripts.pory"
	lockall
# 186 "data/maps/BeginnerClearing/scripts.pory"
	clearflag FLAG_HIDE_CLEARING_NPCS
# 187 "data/maps/BeginnerClearing/scripts.pory"
	speakername JirachiName
# 188 "data/maps/BeginnerClearing/scripts.pory"
	msgbox BeginnerClearing_EventScript_JirachiIntro_Text_0
# 189 "data/maps/BeginnerClearing/scripts.pory"
	playse SE_SELECT
# 190 "data/maps/BeginnerClearing/scripts.pory"
	delay 10
# 191 "data/maps/BeginnerClearing/scripts.pory"
	applymovement LOCALID_PLAYER, BeginnerClearing_QuestionMark
# 192 "data/maps/BeginnerClearing/scripts.pory"
	playse SE_PIN
# 193 "data/maps/BeginnerClearing/scripts.pory"
	waitmovement 0
# 194 "data/maps/BeginnerClearing/scripts.pory"
	delay 50
# 195 "data/maps/BeginnerClearing/scripts.pory"
	msgbox BeginnerClearing_EventScript_JirachiIntro_Text_1, MSGBOX_AUTOCLOSE
# 196 "data/maps/BeginnerClearing/scripts.pory"
	playse SE_SELECT
# 197 "data/maps/BeginnerClearing/scripts.pory"
	addobject ProfMyra
# 198 "data/maps/BeginnerClearing/scripts.pory"
	applymovement ProfMyra, BeginnerClearing_MyraRunsInA
# 199 "data/maps/BeginnerClearing/scripts.pory"
	waitmovement 0
# 200 "data/maps/BeginnerClearing/scripts.pory"
	applymovement ProfMyra, BeginnerClearing_ExclamationMark
# 201 "data/maps/BeginnerClearing/scripts.pory"
	playse SE_PIN
# 202 "data/maps/BeginnerClearing/scripts.pory"
	waitmovement 0
# 203 "data/maps/BeginnerClearing/scripts.pory"
	delay 50
# 204 "data/maps/BeginnerClearing/scripts.pory"
	applymovement ProfMyra, BeginnerClearing_MyraRunsInB
# 205 "data/maps/BeginnerClearing/scripts.pory"
	waitmovement 0
# 206 "data/maps/BeginnerClearing/scripts.pory"
	addobject MyrasBag
# 207 "data/maps/BeginnerClearing/scripts.pory"
	speakername ProfMyraName
# 208 "data/maps/BeginnerClearing/scripts.pory"
	msgbox BeginnerClearing_EventScript_JirachiIntro_Text_2
# 209 "data/maps/BeginnerClearing/scripts.pory"
	playse SE_SELECT
# 210 "data/maps/BeginnerClearing/scripts.pory"
	msgbox BeginnerClearing_EventScript_JirachiIntro_Text_3
# 211 "data/maps/BeginnerClearing/scripts.pory"
	playse SE_USE_ITEM
# 212 "data/maps/BeginnerClearing/scripts.pory"
	waitse
# 213 "data/maps/BeginnerClearing/scripts.pory"
	msgbox BeginnerClearing_EventScript_JirachiIntro_Text_4
# 216 "data/maps/BeginnerClearing/scripts.pory"
	playse SE_SELECT
# 217 "data/maps/BeginnerClearing/scripts.pory"
	applymovement ProfMyra, BeginnerClearing_EventScript_JirachiIntro_Movement_0
# 218 "data/maps/BeginnerClearing/scripts.pory"
	waitmovement 0
# 219 "data/maps/BeginnerClearing/scripts.pory"
	msgbox BeginnerClearing_EventScript_JirachiIntro_Text_5
# 220 "data/maps/BeginnerClearing/scripts.pory"
	msgbox BeginnerClearing_EventScript_JirachiIntro_Text_6
# 221 "data/maps/BeginnerClearing/scripts.pory"
	msgbox BeginnerClearing_EventScript_JirachiIntro_Text_7, MSGBOX_AUTOCLOSE
# 227 "data/maps/BeginnerClearing/scripts.pory"
	playse SE_SELECT
# 228 "data/maps/BeginnerClearing/scripts.pory"
	addobject GruntA
# 229 "data/maps/BeginnerClearing/scripts.pory"
	addobject GruntB
# 230 "data/maps/BeginnerClearing/scripts.pory"
	applymovement GruntA, BeginnerClearing_GruntAWalksIn
# 231 "data/maps/BeginnerClearing/scripts.pory"
	applymovement GruntB, BeginnerClearing_GruntBWalksIn
# 232 "data/maps/BeginnerClearing/scripts.pory"
	waitmovement 0
# 233 "data/maps/BeginnerClearing/scripts.pory"
	playbgm MUS_RG_ROCKET_HIDEOUT, FALSE
# 234 "data/maps/BeginnerClearing/scripts.pory"
	delay 40
# 235 "data/maps/BeginnerClearing/scripts.pory"
	applymovement GruntA, BeginnerClearing_ExclamationMark
# 236 "data/maps/BeginnerClearing/scripts.pory"
	applymovement GruntB, BeginnerClearing_ExclamationMark
# 237 "data/maps/BeginnerClearing/scripts.pory"
	playse SE_PIN
# 238 "data/maps/BeginnerClearing/scripts.pory"
	waitmovement 0
# 239 "data/maps/BeginnerClearing/scripts.pory"
	delay 50
# 240 "data/maps/BeginnerClearing/scripts.pory"
	applymovement LOCALID_PLAYER, BeginnerClearing_EventScript_JirachiIntro_Movement_0
# 241 "data/maps/BeginnerClearing/scripts.pory"
	applymovement ProfMyra, BeginnerClearing_EventScript_JirachiIntro_Movement_0
# 242 "data/maps/BeginnerClearing/scripts.pory"
	special SpawnCameraObject
# 243 "data/maps/BeginnerClearing/scripts.pory"
	applymovement LOCALID_CAMERA, BeginnerClearing_EventScript_JirachiIntro_Movement_1
# 244 "data/maps/BeginnerClearing/scripts.pory"
	waitmovement 0
# 245 "data/maps/BeginnerClearing/scripts.pory"
	speakername GruntAName
# 246 "data/maps/BeginnerClearing/scripts.pory"
	msgbox BeginnerClearing_EventScript_JirachiIntro_Text_8
# 247 "data/maps/BeginnerClearing/scripts.pory"
	playse SE_SELECT
# 248 "data/maps/BeginnerClearing/scripts.pory"
	speakername GruntBName
# 249 "data/maps/BeginnerClearing/scripts.pory"
	msgbox BeginnerClearing_EventScript_JirachiIntro_Text_9, MSGBOX_AUTOCLOSE
# 250 "data/maps/BeginnerClearing/scripts.pory"
	playse SE_SELECT
# 251 "data/maps/BeginnerClearing/scripts.pory"
	delay 10
# 252 "data/maps/BeginnerClearing/scripts.pory"
	applymovement LOCALID_PLAYER, BeginnerClearing_ExclamationMark
# 253 "data/maps/BeginnerClearing/scripts.pory"
	applymovement ProfMyra, BeginnerClearing_ExclamationMark
# 254 "data/maps/BeginnerClearing/scripts.pory"
	playse SE_PIN
# 255 "data/maps/BeginnerClearing/scripts.pory"
	waitmovement 0
# 256 "data/maps/BeginnerClearing/scripts.pory"
	delay 50
# 257 "data/maps/BeginnerClearing/scripts.pory"
	applymovement LOCALID_PLAYER, BeginnerClearing_PlayerRunsInFrontOfGrunts
# 258 "data/maps/BeginnerClearing/scripts.pory"
	applymovement LOCALID_CAMERA, BeginnerClearing_EventScript_JirachiIntro_Movement_2
# 259 "data/maps/BeginnerClearing/scripts.pory"
	waitmovement 0
# 260 "data/maps/BeginnerClearing/scripts.pory"
	delay 30
# 261 "data/maps/BeginnerClearing/scripts.pory"
	special RemoveCameraObject
# 262 "data/maps/BeginnerClearing/scripts.pory"
	speakername GruntAName
# 263 "data/maps/BeginnerClearing/scripts.pory"
	msgbox BeginnerClearing_EventScript_JirachiIntro_Text_10
# 264 "data/maps/BeginnerClearing/scripts.pory"
	playse SE_SELECT
# 265 "data/maps/BeginnerClearing/scripts.pory"
	speakername GruntBName
# 266 "data/maps/BeginnerClearing/scripts.pory"
	msgbox BeginnerClearing_EventScript_JirachiIntro_Text_11
# 267 "data/maps/BeginnerClearing/scripts.pory"
	playse SE_SELECT
# 268 "data/maps/BeginnerClearing/scripts.pory"
	speakername ProfMyraName
# 269 "data/maps/BeginnerClearing/scripts.pory"
	msgbox BeginnerClearing_EventScript_JirachiIntro_Text_12
# 270 "data/maps/BeginnerClearing/scripts.pory"
	playse SE_SELECT
# 271 "data/maps/BeginnerClearing/scripts.pory"
	speakername GruntBName
# 272 "data/maps/BeginnerClearing/scripts.pory"
	msgbox BeginnerClearing_EventScript_JirachiIntro_Text_13
# 273 "data/maps/BeginnerClearing/scripts.pory"
	playse SE_SELECT
# 274 "data/maps/BeginnerClearing/scripts.pory"
	speakername GruntAName
# 275 "data/maps/BeginnerClearing/scripts.pory"
	msgbox BeginnerClearing_EventScript_JirachiIntro_Text_14, MSGBOX_AUTOCLOSE
# 276 "data/maps/BeginnerClearing/scripts.pory"
	playse SE_SELECT
# 277 "data/maps/BeginnerClearing/scripts.pory"
	applymovement ProfMyra, BeginnerClearing_ProfMyraWalksToPlayer
# 278 "data/maps/BeginnerClearing/scripts.pory"
	waitmovement 0
# 279 "data/maps/BeginnerClearing/scripts.pory"
	speakername ProfMyraName
# 280 "data/maps/BeginnerClearing/scripts.pory"
	msgbox BeginnerClearing_EventScript_JirachiIntro_Text_15
# 285 "data/maps/BeginnerClearing/scripts.pory"
	setobjectxyperm GruntA, 7, 13
# 286 "data/maps/BeginnerClearing/scripts.pory"
	setobjectxyperm GruntB, 7, 14
# 287 "data/maps/BeginnerClearing/scripts.pory"
	setobjectxyperm ProfMyra, 11, 14
# 288 "data/maps/BeginnerClearing/scripts.pory"
	releaseall
	return


BeginnerClearing_EventScript_MyrasBag::
# 292 "data/maps/BeginnerClearing/scripts.pory"
	lockall
# 293 "data/maps/BeginnerClearing/scripts.pory"
	fadescreen FADE_TO_BLACK
# 294 "data/maps/BeginnerClearing/scripts.pory"
	setflag FLAG_SYS_POKEMON_GET
# 295 "data/maps/BeginnerClearing/scripts.pory"
	special ChooseStarter
# 296 "data/maps/BeginnerClearing/scripts.pory"
	waitstate
# 297 "data/maps/BeginnerClearing/scripts.pory"
	call BeginnerClearing_EventScript_GruntABattle
# 298 "data/maps/BeginnerClearing/scripts.pory"
	releaseall
	return


BeginnerClearing_EventScript_GruntABattle::
# 302 "data/maps/BeginnerClearing/scripts.pory"
	lockall
# 303 "data/maps/BeginnerClearing/scripts.pory"
	applymovement GruntA, BeginnerClearing_GruntARunsToPlayer
# 304 "data/maps/BeginnerClearing/scripts.pory"
	applymovement GruntB, BeginnerClearing_GruntBRunsToProfMyra
# 305 "data/maps/BeginnerClearing/scripts.pory"
	waitmovement 0
# 306 "data/maps/BeginnerClearing/scripts.pory"
	switch VAR_FACING
# 307 "data/maps/BeginnerClearing/scripts.pory"
	case DIR_EAST, BeginnerClearing_EventScript_GruntABattle_3
# 309 "data/maps/BeginnerClearing/scripts.pory"
	case DIR_SOUTH, BeginnerClearing_EventScript_GruntABattle_4
# 311 "data/maps/BeginnerClearing/scripts.pory"
	case DIR_WEST, BeginnerClearing_EventScript_GruntABattle_5
# 313 "data/maps/BeginnerClearing/scripts.pory"
	case DIR_NORTH, BeginnerClearing_EventScript_GruntABattle_6
BeginnerClearing_EventScript_GruntABattle_1:
# 316 "data/maps/BeginnerClearing/scripts.pory"
	waitmovement LOCALID_PLAYER
# 317 "data/maps/BeginnerClearing/scripts.pory"
	applymovement ProfMyra, BeginnerClearing_EventScript_JirachiIntro_Movement_0
# 318 "data/maps/BeginnerClearing/scripts.pory"
	trainerbattle_single TRAINER_GRUNT_MAGMA_HIDEOUT_14, BeginnerClearing_EventScript_GruntABattle_Text_0, BeginnerClearing_EventScript_GruntABattle_Text_1, BeginnerClearing_EventScript_AfterBattle
# 319 "data/maps/BeginnerClearing/scripts.pory"
	releaseall
	return

BeginnerClearing_EventScript_GruntABattle_3:
# 308 "data/maps/BeginnerClearing/scripts.pory"
	applymovement LOCALID_PLAYER, BeginnerClearing_WalkToGruntA_LeftSideOfBag
	goto BeginnerClearing_EventScript_GruntABattle_1

BeginnerClearing_EventScript_GruntABattle_4:
# 310 "data/maps/BeginnerClearing/scripts.pory"
	applymovement LOCALID_PLAYER, BeginnerClearing_WalkToGruntA_TopSideOfBag
	goto BeginnerClearing_EventScript_GruntABattle_1

BeginnerClearing_EventScript_GruntABattle_5:
# 312 "data/maps/BeginnerClearing/scripts.pory"
	applymovement LOCALID_PLAYER, BeginnerClearing_WalkToGruntA_RightSideOfBag
	goto BeginnerClearing_EventScript_GruntABattle_1

BeginnerClearing_EventScript_GruntABattle_6:
# 314 "data/maps/BeginnerClearing/scripts.pory"
	applymovement LOCALID_PLAYER, BeginnerClearing_WalkToGruntA_BottomSideOfBag
	goto BeginnerClearing_EventScript_GruntABattle_1


BeginnerClearing_EventScript_AfterBattle::
# 323 "data/maps/BeginnerClearing/scripts.pory"
	lockall
# 324 "data/maps/BeginnerClearing/scripts.pory"
	speakername GruntAName
# 325 "data/maps/BeginnerClearing/scripts.pory"
	msgbox BeginnerClearing_EventScript_AfterBattle_Text_0, MSGBOX_AUTOCLOSE
# 327 "data/maps/BeginnerClearing/scripts.pory"
	playse SE_SELECT
# 328 "data/maps/BeginnerClearing/scripts.pory"
	applymovement GruntA, BeginnerClearing_EventScript_AfterBattle_Movement_0
# 329 "data/maps/BeginnerClearing/scripts.pory"
	waitmovement 0
# 330 "data/maps/BeginnerClearing/scripts.pory"
	speakername GruntBName
# 331 "data/maps/BeginnerClearing/scripts.pory"
	msgbox BeginnerClearing_EventScript_AfterBattle_Text_1, MSGBOX_AUTOCLOSE
# 332 "data/maps/BeginnerClearing/scripts.pory"
	playse SE_SELECT
# 333 "data/maps/BeginnerClearing/scripts.pory"
	applymovement GruntB, BeginnerClearing_EventScript_AfterBattle_Movement_0
# 334 "data/maps/BeginnerClearing/scripts.pory"
	waitmovement 0
# 335 "data/maps/BeginnerClearing/scripts.pory"
	applymovement ProfMyra, BeginnerClearing_EventScript_AfterBattle_Movement_1
# 338 "data/maps/BeginnerClearing/scripts.pory"
	applymovement LOCALID_PLAYER, BeginnerClearing_EventScript_AfterBattle_Movement_2
# 339 "data/maps/BeginnerClearing/scripts.pory"
	waitmovement 0
# 340 "data/maps/BeginnerClearing/scripts.pory"
	speakername ProfMyraName
# 341 "data/maps/BeginnerClearing/scripts.pory"
	msgbox BeginnerClearing_EventScript_AfterBattle_Text_2, MSGBOX_AUTOCLOSE
# 344 "data/maps/BeginnerClearing/scripts.pory"
	playse SE_SELECT
# 345 "data/maps/BeginnerClearing/scripts.pory"
	setflag FLAG_CAN_LEAVE_BEGINNER_CLEARING
# 346 "data/maps/BeginnerClearing/scripts.pory"
	setflag FLAG_HIDE_CLEARING_NPCS
# 347 "data/maps/BeginnerClearing/scripts.pory"
	setflag FLAG_HIDE_CLEARING_JIRACHI
# 348 "data/maps/BeginnerClearing/scripts.pory"
	special HealPlayerParty
# 349 "data/maps/BeginnerClearing/scripts.pory"
	warpsilent MAP_LUMEN_VILLAGE_PROFESSOR_MYRAS_LAB, 6, 12
# 350 "data/maps/BeginnerClearing/scripts.pory"
	releaseall
	return


BeginnerClearing_EventScript_LookForJirachiFromA::
# 354 "data/maps/BeginnerClearing/scripts.pory"
	compare VAR_INTRO_SCENE, 4
	goto_if_eq BeginnerClearing_EventScript_LookForJirachiFromA_1
	return

BeginnerClearing_EventScript_LookForJirachiFromA_1:
# 355 "data/maps/BeginnerClearing/scripts.pory"
	lockall
# 356 "data/maps/BeginnerClearing/scripts.pory"
	setvar VAR_INTRO_SCENE, 5
# 357 "data/maps/BeginnerClearing/scripts.pory"
	hidefollower
# 358 "data/maps/BeginnerClearing/scripts.pory"
	applymovement LOCALID_PLAYER, BeginnerClearing_PlayerWalksIn_LookForJirachiFromA
# 359 "data/maps/BeginnerClearing/scripts.pory"
	waitmovement 0
# 360 "data/maps/BeginnerClearing/scripts.pory"
	call BeginnerClearing_EventScript_JirachiPlayerFirstDialogue
# 361 "data/maps/BeginnerClearing/scripts.pory"
	releaseall
	return


BeginnerClearing_EventScript_LookForJirachiFromB::
# 366 "data/maps/BeginnerClearing/scripts.pory"
	compare VAR_INTRO_SCENE, 4
	goto_if_eq BeginnerClearing_EventScript_LookForJirachiFromB_1
	return

BeginnerClearing_EventScript_LookForJirachiFromB_1:
# 367 "data/maps/BeginnerClearing/scripts.pory"
	lockall
# 368 "data/maps/BeginnerClearing/scripts.pory"
	setvar VAR_INTRO_SCENE, 5
# 369 "data/maps/BeginnerClearing/scripts.pory"
	hidefollower
# 370 "data/maps/BeginnerClearing/scripts.pory"
	applymovement LOCALID_PLAYER, BeginnerClearing_PlayerWalksIn_LookForJirachiFromB
# 371 "data/maps/BeginnerClearing/scripts.pory"
	waitmovement 0
# 372 "data/maps/BeginnerClearing/scripts.pory"
	call BeginnerClearing_EventScript_JirachiPlayerFirstDialogue
# 373 "data/maps/BeginnerClearing/scripts.pory"
	releaseall
	return


BeginnerClearing_EventScript_JirachiPlayerFirstDialogue::
# 378 "data/maps/BeginnerClearing/scripts.pory"
	lockall
# 379 "data/maps/BeginnerClearing/scripts.pory"
	applymovement LOCALID_PLAYER, BeginnerClearing_ExclamationMark
# 380 "data/maps/BeginnerClearing/scripts.pory"
	playse SE_PIN
# 381 "data/maps/BeginnerClearing/scripts.pory"
	waitmovement 0
# 382 "data/maps/BeginnerClearing/scripts.pory"
	clearflag FLAG_HIDE_CLEARING_JIRACHI2
# 383 "data/maps/BeginnerClearing/scripts.pory"
	addobject jirachi_intro_2
# 384 "data/maps/BeginnerClearing/scripts.pory"
	applymovement jirachi_intro_2, BeginnerClearing_EventScript_JirachiPlayerFirstDialogue_Movement_0
# 385 "data/maps/BeginnerClearing/scripts.pory"
	waitmovement 0
# 386 "data/maps/BeginnerClearing/scripts.pory"
	speakername JirachiName
# 387 "data/maps/BeginnerClearing/scripts.pory"
	msgbox BeginnerClearing_EventScript_JirachiPlayerFirstDialogue_Text_0
# 413 "data/maps/BeginnerClearing/scripts.pory"
	fadescreenswapbuffers FADE_TO_WHITE
# 414 "data/maps/BeginnerClearing/scripts.pory"
	setflag FLAG_HIDE_CLEARING_JIRACHI2
# 415 "data/maps/BeginnerClearing/scripts.pory"
	setflag FLAG_HIDE_MYRA_IN_LAB
# 416 "data/maps/BeginnerClearing/scripts.pory"
	removeobject jirachi_intro_2
# 417 "data/maps/BeginnerClearing/scripts.pory"
	fadescreenswapbuffers FADE_FROM_WHITE
# 418 "data/maps/BeginnerClearing/scripts.pory"
	completequest QUEST_1_MEDS_FOR_JIRACHI
# 419 "data/maps/BeginnerClearing/scripts.pory"
	startquest QUEST_2_STARBOUND_OATH
# 420 "data/maps/BeginnerClearing/scripts.pory"
	subquestmenu QUEST_MENU_SET_ACTIVE, QUEST_2_STARBOUND_OATH, SUB_QUEST_GO_TO_ZENITH_CITY
# 421 "data/maps/BeginnerClearing/scripts.pory"
	openquestmenu
# 422 "data/maps/BeginnerClearing/scripts.pory"
	releaseall
	return


# 217 "data/maps/BeginnerClearing/scripts.pory"
BeginnerClearing_EventScript_JirachiIntro_Movement_0:
# 217 "data/maps/BeginnerClearing/scripts.pory"
	face_left
	step_end

# 243 "data/maps/BeginnerClearing/scripts.pory"
BeginnerClearing_EventScript_JirachiIntro_Movement_1:
# 243 "data/maps/BeginnerClearing/scripts.pory"
	walk_diag_southwest
# 243 "data/maps/BeginnerClearing/scripts.pory"
	walk_diag_southwest
	step_end

# 258 "data/maps/BeginnerClearing/scripts.pory"
BeginnerClearing_EventScript_JirachiIntro_Movement_2:
# 258 "data/maps/BeginnerClearing/scripts.pory"
	walk_right
	step_end

# 328 "data/maps/BeginnerClearing/scripts.pory"
BeginnerClearing_EventScript_AfterBattle_Movement_0:
# 328 "data/maps/BeginnerClearing/scripts.pory"
	walk_fast_left
# 328 "data/maps/BeginnerClearing/scripts.pory"
	walk_fast_left
# 328 "data/maps/BeginnerClearing/scripts.pory"
	walk_fast_left
# 328 "data/maps/BeginnerClearing/scripts.pory"
	walk_fast_left
# 328 "data/maps/BeginnerClearing/scripts.pory"
	walk_fast_left
# 328 "data/maps/BeginnerClearing/scripts.pory"
	walk_fast_left
# 328 "data/maps/BeginnerClearing/scripts.pory"
	walk_fast_left
# 328 "data/maps/BeginnerClearing/scripts.pory"
	walk_fast_left
# 328 "data/maps/BeginnerClearing/scripts.pory"
	walk_fast_left
# 328 "data/maps/BeginnerClearing/scripts.pory"
	walk_fast_left
	step_end

# 335 "data/maps/BeginnerClearing/scripts.pory"
BeginnerClearing_EventScript_AfterBattle_Movement_1:
# 336 "data/maps/BeginnerClearing/scripts.pory"
	walk_right
# 337 "data/maps/BeginnerClearing/scripts.pory"
	face_up
	step_end

# 338 "data/maps/BeginnerClearing/scripts.pory"
BeginnerClearing_EventScript_AfterBattle_Movement_2:
# 338 "data/maps/BeginnerClearing/scripts.pory"
	face_down
	step_end

# 384 "data/maps/BeginnerClearing/scripts.pory"
BeginnerClearing_EventScript_JirachiPlayerFirstDialogue_Movement_0:
# 384 "data/maps/BeginnerClearing/scripts.pory"
	walk_slow_down
# 384 "data/maps/BeginnerClearing/scripts.pory"
	walk_slow_down
# 384 "data/maps/BeginnerClearing/scripts.pory"
	walk_slow_down
# 384 "data/maps/BeginnerClearing/scripts.pory"
	walk_slow_down
# 384 "data/maps/BeginnerClearing/scripts.pory"
	walk_slow_down
# 384 "data/maps/BeginnerClearing/scripts.pory"
	walk_slow_down
# 384 "data/maps/BeginnerClearing/scripts.pory"
	walk_slow_down
# 384 "data/maps/BeginnerClearing/scripts.pory"
	walk_slow_down
	step_end

BeginnerClearing_EventScript_ProfMyra_Text_0:
# 165 "data/maps/BeginnerClearing/scripts.pory"
	.string "I will lend you one of my Pokémon so\nwe can defend this Jirachi together.\l"
	.string "Please grab a Pokéball from my bag.$"

BeginnerClearing_EventScript_GruntA_Text_0:
# 171 "data/maps/BeginnerClearing/scripts.pory"
	.string "Fool! Hand Jirachi over and don't\n"
	.string "interfere!$"

BeginnerClearing_EventScript_GruntB_Text_0:
# 176 "data/maps/BeginnerClearing/scripts.pory"
	.string "Don't meddle where you aren't supposed\n"
	.string "to!$"

BeginnerClearing_EventScript_JirachiIntro_Text_0:
# 188 "data/maps/BeginnerClearing/scripts.pory"
	.string "{COLOR RED}Help… they're coming after me…$"

BeginnerClearing_EventScript_JirachiIntro_Text_1:
# 195 "data/maps/BeginnerClearing/scripts.pory"
	.string "{COLOR RED}They took my friend… Help…$"

BeginnerClearing_EventScript_JirachiIntro_Text_2:
# 208 "data/maps/BeginnerClearing/scripts.pory"
	.string "Is that a Jirachi? Oh, it's hurt!$"

BeginnerClearing_EventScript_JirachiIntro_Text_3:
# 210 "data/maps/BeginnerClearing/scripts.pory"
	.string "Quick, I have a Potion!$"

BeginnerClearing_EventScript_JirachiIntro_Text_4:
# 213 "data/maps/BeginnerClearing/scripts.pory"
	.string "It should be okay for now, but it needs\n"
	.string "rest.\p"
	.string "The poor thing's definitely in bad\n"
	.string "shape.\p"
	.string "I wonder what happened…$"

BeginnerClearing_EventScript_JirachiIntro_Text_5:
# 219 "data/maps/BeginnerClearing/scripts.pory"
	.string "What's your name?$"

BeginnerClearing_EventScript_JirachiIntro_Text_6:
# 220 "data/maps/BeginnerClearing/scripts.pory"
	.string "…$"

BeginnerClearing_EventScript_JirachiIntro_Text_7:
# 222 "data/maps/BeginnerClearing/scripts.pory"
	.string "{PLAYER}, is it?\p"
	.string "We are lucky you found it so quickly.\p"
	.string "We should take it somewhere to recover.\p"
	.string "…\p"
	.string "You said Jirachi spoke to you? And that\n"
	.string "it said it's being chased?$"

BeginnerClearing_EventScript_JirachiIntro_Text_8:
# 246 "data/maps/BeginnerClearing/scripts.pory"
	.string "Here it is! Grab it!$"

BeginnerClearing_EventScript_JirachiIntro_Text_9:
# 249 "data/maps/BeginnerClearing/scripts.pory"
	.string "You! Hand over that Jirachi!$"

BeginnerClearing_EventScript_JirachiIntro_Text_10:
# 263 "data/maps/BeginnerClearing/scripts.pory"
	.string "Huh? Who are you?$"

BeginnerClearing_EventScript_JirachiIntro_Text_11:
# 266 "data/maps/BeginnerClearing/scripts.pory"
	.string "You think a dweeb like you can get in\n"
	.string "our way?$"

BeginnerClearing_EventScript_JirachiIntro_Text_12:
# 269 "data/maps/BeginnerClearing/scripts.pory"
	.string "And who are you? What do you want with\n"
	.string "this Jirachi?$"

BeginnerClearing_EventScript_JirachiIntro_Text_13:
# 272 "data/maps/BeginnerClearing/scripts.pory"
	.string "That's none of your business, lady!$"

BeginnerClearing_EventScript_JirachiIntro_Text_14:
# 275 "data/maps/BeginnerClearing/scripts.pory"
	.string "Just hand over the Jirachi and no one\n"
	.string "gets hurt!$"

BeginnerClearing_EventScript_JirachiIntro_Text_15:
# 280 "data/maps/BeginnerClearing/scripts.pory"
	.string "{PLAYER}, do you have any Pokémon?\p"
	.string "…\p"
	.string "Hmmm, I see. I think this situation calls\n"
	.string "for special circumstances.\p"
	.string "I will lend you one of my Pokémon so we\n"
	.string "can defend this Jirachi together.\p"
	.string "Please grab a Pokéball from my bag.$"

BeginnerClearing_EventScript_GruntABattle_Text_0:
# 318 "data/maps/BeginnerClearing/scripts.pory"
	.string "You're going down, kid!$"

BeginnerClearing_EventScript_GruntABattle_Text_1:
# 318 "data/maps/BeginnerClearing/scripts.pory"
	.string "Impossible…$"

BeginnerClearing_EventScript_AfterBattle_Text_0:
# 325 "data/maps/BeginnerClearing/scripts.pory"
	.string "How is this possible!?\p"
	.string "You little brat… You'll regret this!$"

BeginnerClearing_EventScript_AfterBattle_Text_1:
# 331 "data/maps/BeginnerClearing/scripts.pory"
	.string "You don't mess with Team Eclipse and\n"
	.string "get away with it!$"

BeginnerClearing_EventScript_AfterBattle_Text_2:
# 341 "data/maps/BeginnerClearing/scripts.pory"
	.string "{PLAYER}, you were amazing!\p"
	.string "I'm so glad you were here.\p"
	.string "Now let's take this Jirachi back to my\n"
	.string "lab so it can rest.$"

BeginnerClearing_EventScript_JirachiPlayerFirstDialogue_Text_0:
# 387 "data/maps/BeginnerClearing/scripts.pory"
	.string "{COLOR RED}…you came.\p"
	.string "I wasn't sure you'd hear me, but… you\n"
	.string "did.\p"
	.string "Those people, they tried to take me.\n"
	.string "They hurt me.\p"
	.string "But I'm not the only one.\p"
	.string "There was another. A friend. Like me.\p"
	.string "They took him. Locked him away… and\n"
	.string "twisted his voice.\p"
	.string "His wishes… used for control. For\n"
	.string "silence.\p"
	.string "…I'm still too weak. But I can feel it…\n"
	.string "minds cracking. Dreams bending.\p"
	.string "I need help… I need to save my friend.\n"
	.string "And I need to stop them.\p"
	.string "Will you help me stop them?\p"
	.string "Will you help me bring my friend back?\p"
	.string "…\p"
	.string "Thank you, {PLAYER}.\p"
	.string "He's being held in a place far from here.\p"
	.string "A place of towers and metal… minds\n"
	.string "shine brightly there, but not freely.\p"
	.string "Zenith City, I believe is the name.\p"
	.string "They use him there. To twist thoughts.\n"
	.string "To turn strong hearts into hollow\l"
	.string "voices.\p"
	.string "One by one, they fall under the silence.\p"
	.string "Leaders. Champions. Protectors.\p"
	.string "…If we don't act soon, no one will remain\n"
	.string "untouched.\p"
	.string "I can't go with you… not yet.\p"
	.string "But I'll guide you when I can.\p"
	.string "There are other minds I can still reach.\n"
	.string "Free them, and we'll be closer to saving\l"
	.string "him, and closer to the truth.\p"
	.string "Closer to stopping the silence.\p"
	.string "Thank you for your help, {PLAYER}.\p"
	.string "I'll find you again when I can.$"

ProfMyraName::
# 115 "data/maps/BeginnerClearing/scripts.pory"
	.string "Prof. Myra$"

JirachiName::
# 119 "data/maps/BeginnerClearing/scripts.pory"
	.string "Jirachi$"

GruntAName::
# 123 "data/maps/BeginnerClearing/scripts.pory"
	.string "Stranger 1$"

GruntBName::
# 127 "data/maps/BeginnerClearing/scripts.pory"
	.string "Stranger 2$"
